# Generated by Django 4.2.3 on 2025-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistic',
            name='name',
            field=models.CharField(help_text='통계 이름', max_length=100),
        ),
    ]
