# Generated by Django 4.2.3 on 2025-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CATEGORY',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, help_text='상위 카테고리 ID(없으면 )', max_length=60, null=True)),
                ('name', models.CharField(help_text='카테고리 이름(최대 100자)', max_length=100)),
            ],
        ),
    ]
