# Generated by Django 4.2.3 on 2025-01-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(help_text='광고 게시물 ID', max_length=16)),
                ('start_dt', models.DateTimeField(auto_now_add=True, help_text='시작일시. 이 날짜가 지나면 광고가 시작됩니다.', max_length=20)),
                ('end_dt', models.DateTimeField(auto_now_add=True, help_text='종료일시. 이 날짜가 지나면 상태가 expired로 변경됩니다.', max_length=20)),
                ('status', models.CharField(help_text='광고 상태(active, expired)', max_length=20)),
                ('weight', models.IntegerField(help_text='검색 가중치(이 값이 높을수록 검색 결과 상위에 표시)')),
                ('note', models.TextField(blank=True, help_text='관리자 메모', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOARD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_id', models.CharField(blank=True, help_text='상위 게시판 ID(없으면 공백)', max_length=16, null=True)),
                ('name', models.CharField(help_text='게시판 이름(최대 100자)', max_length=100)),
                ('post_type', models.CharField(help_text='게시물 타입(card, box, list, event, none-게시물 작성 불가, 리다이렉트 안됨)', max_length=20)),
                ('display_permissions', models.CharField(blank=True, help_text='게시판 표시 권한(user, dame, partner, supervisor, sub_supervisor. ,로 구분)', max_length=100, null=True)),
                ('enter_permissions', models.CharField(blank=True, help_text='게시판 접근 권한(user, dame, partner, supervisor, sub_supervisor. ,로 구분)', max_length=100, null=True)),
                ('write_permissions', models.CharField(blank=True, help_text='게시판 작성 권한(user, dame, partner, supervisor, sub_supervisor. ,로 구분)', max_length=100, null=True)),
                ('comment_permissions', models.CharField(blank=True, help_text='게시판 댓글 권한(user, dame, partner, supervisor, sub_supervisor. ,로 구분)', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='COMMENT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(help_text='게시물 ID', max_length=16)),
                ('author_id', models.CharField(help_text='작성자 ID', max_length=60)),
                ('target_comment_id', models.CharField(blank=True, help_text='대상 댓글 ID(없으면 공백)', max_length=16, null=True)),
                ('content', models.TextField(help_text='내용')),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='작성일시')),
            ],
        ),
        migrations.CreateModel(
            name='POST',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('board_id', models.CharField(help_text='게시판 ID', max_length=16)),
                ('author_id', models.CharField(help_text='작성자 ID', max_length=60)),
                ('target_post_id', models.CharField(blank=True, help_text='대상 게시물 ID(없으면 공백)', max_length=16, null=True)),
                ('ad_id', models.CharField(blank=True, help_text='광고 ID(없으면 공백)', max_length=16, null=True)),
                ('title', models.CharField(help_text='제목(최대 100자)', max_length=100)),
                ('content', models.TextField(help_text='내용')),
                ('images', models.TextField(blank=True, help_text='이미지 URL(없으면 공백. ,로 구분)', null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, help_text='작성일시')),
                ('views', models.TextField(blank=True, help_text='조회한 사용자 ID(없으면 공백. ,로 구분)', null=True)),
                ('bookmarks', models.TextField(blank=True, help_text='북마크한 사용자 ID(없으면 공백. ,로 구분)', null=True)),
                ('weight', models.IntegerField(help_text='가중치(이 값이 높을수록 상위에 표시)')),
            ],
        ),
    ]
